apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-app.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "mern-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "mern-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        {{- include "mern-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mern-app.fullname" . }}-config
            - secretRef:
                name: {{ include "mern-app.fullname" . }}-secret
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
