prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

coreDns:
  enabled: true
kubeDns:
  enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local:80 
      jsonData:
        maxLines: 1000
  persistence:
    enabled: true