deploymentMode: SingleBinary

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 1

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem

gateway:
  enabled: false

monitoring:
  dashboards:
    enabled: true

promtail:
  enabled: true